apiVersion: v1
kind: Service
metadata:
  name: app-presente-db-service
  namespace: app-chamada-production
spec:
  selector:
    app: app-presente-db
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  type: ClusterIP
