name: Deploy PostgreSQL

on:
  push:
    branches: [main, dev]
  pull_request:
    types: [closed]
    branches: [main, dev]

env:
  PROJECT_ID: app-chamada-5706
  ZONE: us-central1-a
  CLUSTER_NAME: app-prod-1720e7a1
  NAMESPACE: production-app-presente

jobs:
  deploy-db:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}

      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Install GKE Auth Plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin -q

      - name: Get cluster credentials
        run: |
          gcloud container clusters get-credentials ${{ env.CLUSTER_NAME }} \
            --zone ${{ env.ZONE }} \
            --project ${{ env.PROJECT_ID }}

      - name: Create namespace (if not exists)
        run: |
          kubectl get namespace ${{ env.NAMESPACE }} || \
          kubectl create namespace ${{ env.NAMESPACE }}

      - name: Deploy Database Secrets
        run: |
          kubectl apply -f production/db-secret.yaml

      - name: Deploy Persistent Volume Claim
        run: |
          kubectl apply -f production/db-pvc.yaml

      - name: Deploy Database Service
        run: |
          kubectl apply -f production/db-service.yaml

      - name: Deploy Database Deployment
        run: |
          kubectl apply -f production/db-deployment.yaml
