name: Deploy PostgreSQL (Stage)

on:
  push:
    branches: [main, dev]
  pull_request:
    types: [closed]
    branches: [main, dev]

env:
  PROJECT_ID: app-chamada-stage
  CLUSTER_NAME: app-chamada-stage
  ZONE: us-west1-a
  REGION: us-west1
  NAMESPACE: app-chamada-stage

jobs:
  deploy-db:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON_STAGE }}

      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Install GKE Auth Plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin -q

      - name: Get cluster credentials
        run: |
          gcloud container clusters get-credentials ${{ env.CLUSTER_NAME }} \
            --zone ${{ env.ZONE }} \
            --project ${{ env.PROJECT_ID }}

      - name: Create namespace (if not exists)
        run: |
          kubectl get namespace ${{ env.NAMESPACE }} || \
          kubectl create namespace ${{ env.NAMESPACE }}

      - name: Deploy Database Secrets
        run: |
          kubectl apply -f stage/db-secret.yaml -n ${{ env.NAMESPACE }}

      - name: Deploy Persistent Volume Claim
        run: |
          kubectl apply -f stage/db-pvc.yaml -n ${{ env.NAMESPACE }}

      - name: Deploy Database Service
        run: |
          kubectl apply -f stage/db-service.yaml -n ${{ env.NAMESPACE }}

      - name: Deploy Database Deployment
        run: |
          kubectl apply -f stage/db-deployment.yaml -n ${{ env.NAMESPACE }}
